# -*- coding: utf-8 -*-
"""Atomic Habit Tracker.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ijTHiGKuZwGu-z7bB5xy87LWSyHb0Qjj

# Atomic Habit Tracker

# Description:
This project is a simple habit tracking application inspired by the concept of building small, consistent habits over time.

The program allows users to add habits, mark them as completed and track their progress in terms of how many times each habit
has been performed.

# Features:
- Add new habits
- Track daily completion
- View progress summary
- Simple and interactive interface

Author: Abeera Iftikhar
Program: HEC Generative AI Training - Cohort 3
"""

# Atomic Habit Tracker

habits = {}
print("🌱 Welcome to Atomic Habit Tracker")

while True:
    print("\n1. Add Habit")
    print("2. Mark Habit as Done")
    print("3. View Progress")
    print("4. Exit")

    choice = input("Enter your choice: ")

    # Add Habit
    if choice == "1":
        habit = input("Enter habit name: ")
        habits[habit] = 0
        print(f"✅ Habit '{habit}' added!")

    # Mark Habit Done
    elif choice == "2":
        habit = input("Enter habit name to mark done: ")
        if habit in habits:
            habits[habit] += 1
            print(f"🔥 Great! '{habit}' completed {habits[habit]} times")
        else:
            print("❌ Habit not found")

    # View Progress
    elif choice == "3":
        print("\n📈 Your Habit Progress:")
        for habit, count in habits.items():
            print(f"{habit}: {count} days")

    # Exit
    elif choice == "4":
        print("Goodbye! Keep building good habits 💪")
        break

    else:
        print("Invalid choice")