# -*- coding: utf-8 -*-
"""Number_Guessing_Game_Python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yZEwaWnyPSLnQobYMrzwIGPDqmclSa3R

## **Number Guessing Game**

This is a simple Python-based game where the computer randomly selects
a number between 1 and 100, and the user tries to guess it.

The program provides hints whether the guessed number is too high or too low.
It continues until the correct number is guessed.

# Features:
- Random number generation
- User interaction
- Hint system (high/low)
- Attempt counter

Author: Abeera Iftikhar
Program: HEC Generative AI Training - Cohort 3
"""

import random

print(" Welcome to Number Guessing Game!")

# Computer selects a random number
secret_number = random.randint(1, 100)

attempts = 0

while True:
    guess = int(input("\nGuess a number between 1 and 100: "))
    attempts += 1

    if guess < secret_number:
        print("Too low! Try again.")

    elif guess > secret_number:
        print("Too high! Try again.")

    else:
        print(f"🎉 Congratulations! You guessed it in {attempts} attempts.")
        break