# -*- coding: utf-8 -*-
"""Alarm Clock in Python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XjkKTXN6yfSsJS_dq5zDhoo88ISoG7Nw

## **Alarm Clock in Python**

 This project is a simple alarm clock program that allows the user
to set a specific time. The program continuously checks the current system time and triggers an alert when it matches the alarm time.

# Features:
- User sets alarm time (HH:MM:SS)
- Real-time clock display
- Alert notification when time matches
- Uses time module

Author: Abeera Iftikhar
Program: HEC Generative AI Training - Cohort 3
"""

import time

print("⏰ Alarm Clock")

# Get alarm time from user
alarm_time = input("Set alarm time (HH:MM:SS, 24-hour format): ")

print("Alarm set for", alarm_time)

while True:
    current_time = time.strftime("%H:%M:%S")
    print("Current Time:", current_time)

    # Check if current time matches alarm time
    if current_time == alarm_time:
        print("🔔 Wake up! Alarm ringing!")

        # Simple alert sound (works in some environments)
        for i in range(5):
            print("\a")  # beep sound
            time.sleep(1)
        break

    time.sleep(1)