# -*- coding: utf-8 -*-
"""Weather App.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/112zEZ_YEmxWTPpQdXOav9pGtskRFfYAW

## Weather App using Python & Gradio

This Python script implements an interactive weather application using the Gradio framework and the OpenWeatherMap API. The application allows users to input a city name and retrieve real-time weather information including temperature, humidity, and atmospheric conditions.

The script sends API requests to fetch live weather data, processes the JSON response, and dynamically displays the results through a user-friendly web interface. The interface is designed using Gradio Blocks with custom HTML styling to enhance visual appearance and improve user experience.

Key features include:

* Real-time weather data retrieval based on user input
* Display of temperature (°C), humidity (%), and weather description
* Error handling for invalid city names or API issues
* Interactive UI with buttons and styled output
* Integration of emojis/icons for better visualization

This project demonstrates the integration of APIs with Python, basic data handling, and frontend interface design using Gradio, making it a strong beginner-to-intermediate level application for portfolio development.

### Author: Abeera Iftikhar Program: HEC Generative AI Training - Cohort 3
"""

import requests
import gradio as gr

API_KEY = "43c52e6baa6b907415b4bdb549b48199"

def get_weather(city):
    url = f"http://api.openweathermap.org/data/2.5/weather?q={city}&appid={API_KEY}&units=metric"

    response = requests.get(url)
    data = response.json()

    if response.status_code != 200:
        return "❌ City not found"

    city_name = data["name"]
    temp = data["main"]["temp"]
    humidity = data["main"]["humidity"]
    desc = data["weather"][0]["description"].title()

    return f"""
    <div style="text-align:center;">
        <h2>🌍 {city_name}</h2>
        <h1 style="font-size:50px;">{temp}°C</h1>
        <p>🌥 {desc}</p>
        <p>💧 Humidity: {humidity}%</p>
    </div>
    """

with gr.Blocks(theme=gr.themes.Soft()) as app:
    gr.Markdown("# 🌦 Beautiful Weather App")

    city = gr.Textbox(label="Enter City Name", placeholder="e.g. Faisalabad")
    output = gr.HTML()

    btn = gr.Button("Get Weather 🌤")

    btn.click(get_weather, inputs=city, outputs=output)

app.launch(share=True)

def get_icon(description):
    if "cloud" in description:
        return "☁️"
    elif "rain" in description:
        return "🌧"
    elif "clear" in description:
        return "☀️"
    else:
        return "🌤"
return f"""

<div style="text-align:center;">
    <h2>🌍 {city_name}</h2>
    <h1 style="font-size:50px;">{temp}\u00B0C</h1>
    <p>💧 Humidity: {humidity}%</p>
</div>
"""

btn.click(get_weather, inputs=city, outputs=output, show_progress=True)