# -*- coding: utf-8 -*-
"""Simple Calculator in Python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kjXpHw7B-jN7nphZmFiC_u3e0ZOyHXPA

### 🧮 **Simple Calculator in Python**

This project is a basic command-line calculator built using Python.
It allows users to perform simple arithmetic operations including
addition, subtraction, multiplication, and division.

The program takes user input, performs the selected operation and displays the result. It also includes error handling for invalid inputs such as division by zero.

Author: Abeera Iftikhar
Program: HEC Generative AI Training - Cohort 3
"""

# Simple Calculator in Python

def add(a, b):
    return a + b

def subtract(a, b):
    return a - b

def multiply(a, b):
    return a * b

def divide(a, b):
    if b == 0:
        return "Error! Division by zero."
    return a / b

print("Simple Calculator")
print("Select operation:")
print("1. Add")
print("2. Subtract")
print("3. Multiply")
print("4. Divide")

while True:
    choice = input("\nEnter choice (1/2/3/4): ")

    if choice in ['1', '2', '3', '4']:
        num1 = float(input("Enter first number: "))
        num2 = float(input("Enter second number: "))

        if choice == '1':
            print("Result:", add(num1, num2))

        elif choice == '2':
            print("Result:", subtract(num1, num2))

        elif choice == '3':
            print("Result:", multiply(num1, num2))

        elif choice == '4':
            print("Result:", divide(num1, num2))

    else:
        print("Invalid input")

    next_calc = input("\nDo you want another calculation? (yes/no): ")
    if next_calc.lower() != 'yes':
        print("Calculator closed.")
        break

"""This simple calculator demonstrates the use of basic Python concepts such as functions, conditional statements, loops, and user input handling.
The program allows users to repeatedly perform calculations until they
choose to exit, making it interactive and beginner-friendly.
"""