# -*- coding: utf-8 -*-
"""KEGG_Enrichment_Visualization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17Ngirhd_fQMlvlS43zpSj0bKaSisvfwi

## PROJECT  : GSE147334 — TEX10 Knockdown CRC Analysis
## MODULE   : KEGG Pathway Enrichment Visualization

This processes KEGG pathway enrichment results generated
from DAVID Functional Annotation Chart reports for differentially
expressed genes (DEGs) in TEX10 knockdown colorectal cancer (CRC)
analysis. The workflow integrates both upregulated and
downregulated pathway datasets, performs data cleaning and
filtering, and generates publication-quality visualizations.

## INPUT FILES
• Upregulated DAVID KEGG enrichment CSV report
• Downregulated DAVID KEGG enrichment CSV report

## ANALYSIS WORKFLOW
1. Import DAVID Functional Annotation Chart reports
2. Filter KEGG_PATHWAY category entries
3. Apply significance cutoff (EASE ≤ 0.05)
4. Merge upregulated and downregulated pathway datasets
5. Clean and organize enrichment information
6. Generate KEGG enrichment visualizations:
      - KEGG_Bar_Chart.png
      - KEGG_Bubble_Plot.png
      - KEGG_Combined_Figure.png
7. Export summarized pathway enrichment results:
      - KEGG_All_Pathways_Summary.csv

## DATASET INFORMATION
GEO Accession :
    GSE147334

## Biological Context :
    TEX10 Knockdown in Colorectal Cancer (CRC)

## Species :
    Homo sapiens

## ENRICHMENT SETTINGS
Database Category :
    KEGG_PATHWAY

## Statistical Cutoff :
    EASE Score ≤ 0.05

## OUTPUT SUMMARY
Upregulated Pathways   : 8
Downregulated Pathways : 2

## TOOLS & RESOURCES
• DAVID Bioinformatics Resources
• Python Libraries:
      - Pandas
      - Matplotlib
      - Seaborn

AUTHOR
Abeera Iftikhar
"""

!pip install matplotlib seaborn pandas numpy -q
print("✅ Libraries ready")

from google.colab import files
import pandas as pd
import io

print("👇 Upload BOTH files when prompted:")
print("   1. DAVIDChartReport_Upregulated_Genes CSV")
print("   2. DAVIDChartReport_Downregulated_Genes CSV")
uploaded = files.upload()

df_up, df_dn = None, None
for fname, content in uploaded.items():
    df = pd.read_csv(io.StringIO(content.decode("utf-8")))
    if 'pregulated' in fname or 'UP' in fname.upper():
        df_up = df
        print(f"✅ Upregulated file   : {fname} ({len(df)} pathways)")
    else:
        df_dn = df
        print(f"✅ Downregulated file : {fname} ({len(df)} pathways)")

if df_up is None or df_dn is None:
    print("⚠️  Could not auto-detect files — assigning manually")
    fnames = list(uploaded.keys())
    df_up = pd.read_csv(io.StringIO(uploaded[fnames[0]].decode("utf-8")))
    df_dn = pd.read_csv(io.StringIO(uploaded[fnames[1]].decode("utf-8")))

import numpy as np

# Keep only KEGG pathways
df_up_kegg = df_up[df_up['Category'] == 'KEGG_PATHWAY'].copy()
df_dn_kegg = df_dn[df_dn['Category'] == 'KEGG_PATHWAY'].copy()

df_up_kegg['Direction'] = 'Upregulated'
df_dn_kegg['Direction'] = 'Downregulated'

df_all = pd.concat([df_up_kegg, df_dn_kegg], ignore_index=True)

# Clean term names
df_all['Term_clean'] = df_all['Term'].str.replace(r'hsa\d+:', '', regex=True).str.strip()

# -log10(p-value)
df_all['neglog10p'] = -np.log10(df_all['P-Value'])

# Sort: upregulated by p-value, then downregulated by p-value
df_up_sorted = df_all[df_all['Direction']=='Upregulated'].sort_values('P-Value', ascending=False)
df_dn_sorted = df_all[df_all['Direction']=='Downregulated'].sort_values('P-Value', ascending=False)
df_all = pd.concat([df_dn_sorted, df_up_sorted], ignore_index=True)

print(f"✅ Total pathways: {len(df_all)}")
print(f"   Upregulated  : {len(df_up_kegg)}")
print(f"   Downregulated: {len(df_dn_kegg)}")
print()
display(df_all[['Term_clean','Direction','Count','P-Value','Benjamini','neglog10p']].round(4))

import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import matplotlib.ticker as ticker

fig, ax = plt.subplots(figsize=(13, 8))

# Colors per direction
bar_colors = ['#2980B9' if d == 'Downregulated' else '#C0392B'
              for d in df_all['Direction']]

bars = ax.barh(
    range(len(df_all)),
    df_all['neglog10p'],
    color=bar_colors,
    edgecolor='white',
    linewidth=0.6,
    height=0.65
)

# Significance threshold line p=0.05
sig = -np.log10(0.05)
ax.axvline(x=sig, color='#7F8C8D', linestyle='--',
           linewidth=1.3, alpha=0.8, zorder=5)
ax.text(sig + 0.05, len(df_all) - 0.2, 'p = 0.05',
        fontsize=8.5, color='#7F8C8D', va='top', style='italic')

# Gene count + Benjamini labels on bars
for i, (bar, row) in enumerate(zip(bars, df_all.itertuples())):
    w = bar.get_width()
    # gene count
    ax.text(w + 0.08, i, f'n={row.Count}',
            va='center', ha='left', fontsize=9, color='#2C3E50', fontweight='500')
    # Benjamini label inside bar if significant
    if row.Benjamini < 0.05:
        ax.text(0.08, i, f'FDR={row.Benjamini:.2e}',
                va='center', ha='left', fontsize=7.5,
                color='white', fontweight='bold')

# Y-axis gene names
ax.set_yticks(range(len(df_all)))
ax.set_yticklabels(df_all['Term_clean'], fontsize=10.5)
ax.invert_yaxis()

# Divider between down and up
n_dn = len(df_dn_sorted)
if n_dn > 0:
    ax.axhline(y=n_dn - 0.5, color='#BDC3C7', linewidth=1.2,
               linestyle='-', alpha=0.8)
    ax.text(df_all['neglog10p'].max() * 1.02, n_dn - 0.5,
            '▲ Upregulated', va='bottom', ha='left',
            fontsize=8.5, color='#C0392B', fontweight='bold')
    ax.text(df_all['neglog10p'].max() * 1.02, n_dn - 0.5,
            '▼ Downregulated', va='top', ha='left',
            fontsize=8.5, color='#2980B9', fontweight='bold')

# Axes formatting
ax.set_xlabel('−log₁₀ (P-value)', fontsize=12, labelpad=8)
ax.set_title(
    'KEGG Pathway Enrichment Analysis\n'
    'GSE147334 · TEX10 Knockdown vs Control · HCT116 Colorectal Cancer',
    fontsize=13, fontweight='bold', pad=14
)
ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)
ax.set_xlim(0, df_all['neglog10p'].max() * 1.35)
ax.xaxis.grid(True, linestyle=':', alpha=0.4, color='#BDC3C7')
ax.set_axisbelow(True)

# Legend
up_p = mpatches.Patch(color='#C0392B', label='Upregulated DEGs (n=8 pathways)')
dn_p = mpatches.Patch(color='#2980B9', label='Downregulated DEGs (n=2 pathways)')
ax.legend(handles=[up_p, dn_p], loc='lower right',
          fontsize=9.5, frameon=True, framealpha=0.92,
          edgecolor='#BDC3C7')

plt.tight_layout()
plt.savefig('KEGG_Bar_Chart.png', dpi=300,
            bbox_inches='tight', facecolor='white')
plt.show()
print("✅ Saved: KEGG_Bar_Chart.png")

fig, ax = plt.subplots(figsize=(13, 8))

# Bubble size = gene count (scaled)
max_count = df_all['Count'].max()
bubble_sz  = (df_all['Count'] / max_count) * 700 + 100

# Color = direction; alpha = Benjamini significance
bubble_colors = ['#E74C3C' if d == 'Upregulated' else '#3498DB'
                 for d in df_all['Direction']]
alphas = [0.90 if b < 0.05 else 0.55 for b in df_all['Benjamini']]

for i, (row, sz, col, al) in enumerate(
        zip(df_all.itertuples(), bubble_sz, bubble_colors, alphas)):
    ax.scatter(row.neglog10p, i, s=sz, c=col,
               alpha=al, edgecolors='white',
               linewidths=1.3, zorder=3)

# Significance line
ax.axvline(x=sig, color='#7F8C8D', linestyle='--',
           linewidth=1.3, alpha=0.8, zorder=2)
ax.text(sig + 0.05, -0.6, 'p = 0.05',
        fontsize=8.5, color='#7F8C8D', style='italic')

# Labels
for i, row in enumerate(df_all.itertuples()):
    ax.text(row.neglog10p + 0.15, i,
            f'n={row.Count}  (p={row._7:.2e})',
            va='center', ha='left', fontsize=8.8, color='#2C3E50')

# Divider
if n_dn > 0:
    ax.axhline(y=n_dn - 0.5, color='#BDC3C7',
               linewidth=1.2, linestyle='-', alpha=0.8)

# Y-axis
ax.set_yticks(range(len(df_all)))
ax.set_yticklabels(df_all['Term_clean'], fontsize=10.5)
ax.invert_yaxis()

# Formatting
ax.set_xlabel('−log₁₀ (P-value)', fontsize=12, labelpad=8)
ax.set_title(
    'KEGG Pathway Enrichment Bubble Plot\n'
    'GSE147334 · TEX10 Knockdown vs Control · HCT116 Colorectal Cancer',
    fontsize=13, fontweight='bold', pad=14
)
ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)
ax.set_xlim(0, df_all['neglog10p'].max() * 1.45)
ax.xaxis.grid(True, linestyle=':', alpha=0.4, color='#BDC3C7')
ax.set_axisbelow(True)

# Bubble size legend
for n_val in [4, 7, 9]:
    sz = (n_val / max_count) * 700 + 100
    ax.scatter([], [], s=sz, c='gray', alpha=0.5, label=f'Gene count = {n_val}')

# Direction legend
up_p = mpatches.Patch(color='#E74C3C', label='Upregulated (solid=FDR<0.05)', alpha=0.9)
dn_p = mpatches.Patch(color='#3498DB', label='Downregulated', alpha=0.9)
handles = [up_p, dn_p]
leg1 = ax.legend(handles=handles, loc='lower right', fontsize=9,
                 frameon=True, framealpha=0.92, edgecolor='#BDC3C7',
                 title='Direction', title_fontsize=9)
ax.add_artist(leg1)

plt.tight_layout()
plt.savefig('KEGG_Bubble_Plot.png', dpi=300,
            bbox_inches='tight', facecolor='white')
plt.show()
print("✅ Saved: KEGG_Bubble_Plot.png")

fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(22, 9))
fig.suptitle(
    'KEGG Pathway Enrichment Analysis — GSE147334\n'
    'TEX10 Knockdown vs Negative Control (HCT116 Colorectal Cancer Cells)',
    fontsize=13, fontweight='bold', y=1.02
)

## Panel A — Bar chart
bc = ['#2980B9' if d=='Downregulated' else '#C0392B' for d in df_all['Direction']]
bars = ax1.barh(range(len(df_all)), df_all['neglog10p'],
                color=bc, edgecolor='white', linewidth=0.5, height=0.65)
ax1.axvline(x=sig, color='#7F8C8D', linestyle='--', linewidth=1.2, alpha=0.8)
ax1.text(sig+0.05, len(df_all)-0.3, 'p=0.05',
         fontsize=8, color='#7F8C8D', style='italic')
for i, (bar, row) in enumerate(zip(bars, df_all.itertuples())):
    ax1.text(bar.get_width()+0.06, i, f'n={row.Count}',
             va='center', ha='left', fontsize=8.5, color='#2C3E50')
if n_dn > 0:
    ax1.axhline(y=n_dn-0.5, color='#BDC3C7', linewidth=1, linestyle='-', alpha=0.7)
ax1.set_yticks(range(len(df_all)))
ax1.set_yticklabels(df_all['Term_clean'], fontsize=9.5)
ax1.invert_yaxis()
ax1.set_xlabel('−log₁₀ (P-value)', fontsize=11)
ax1.set_title('A', fontsize=13, fontweight='bold', loc='left')
ax1.spines['top'].set_visible(False)
ax1.spines['right'].set_visible(False)
ax1.set_xlim(0, df_all['neglog10p'].max()*1.3)
ax1.xaxis.grid(True, linestyle=':', alpha=0.4)
ax1.set_axisbelow(True)

## Panel B — Bubble plot
for i, (row, sz, col) in enumerate(zip(df_all.itertuples(), bubble_sz, bubble_colors)):
    al = 0.90 if row.Benjamini < 0.05 else 0.55
    ax2.scatter(row.neglog10p, i, s=sz, c=col,
                alpha=al, edgecolors='white', linewidths=1.2, zorder=3)
ax2.axvline(x=sig, color='#7F8C8D', linestyle='--', linewidth=1.2, alpha=0.8)
for i, row in enumerate(df_all.itertuples()):
    ax2.text(row.neglog10p+0.12, i, f'n={row.Count}',
             va='center', ha='left', fontsize=8.5, color='#2C3E50')
if n_dn > 0:
    ax2.axhline(y=n_dn-0.5, color='#BDC3C7', linewidth=1, linestyle='-', alpha=0.7)
ax2.set_yticks(range(len(df_all)))
ax2.set_yticklabels(df_all['Term_clean'], fontsize=9.5)
ax2.invert_yaxis()
ax2.set_xlabel('−log₁₀ (P-value)', fontsize=11)
ax2.set_title('B', fontsize=13, fontweight='bold', loc='left')
ax2.spines['top'].set_visible(False)
ax2.spines['right'].set_visible(False)
ax2.set_xlim(0, df_all['neglog10p'].max()*1.4)
ax2.xaxis.grid(True, linestyle=':', alpha=0.4)
ax2.set_axisbelow(True)

## Shared legend
up_p = mpatches.Patch(color='#C0392B', label='Upregulated genes', alpha=0.88)
dn_p = mpatches.Patch(color='#2980B9', label='Downregulated genes', alpha=0.88)
fig.legend(handles=[up_p, dn_p], loc='lower center',
           ncol=2, fontsize=10, frameon=True,
           bbox_to_anchor=(0.5, -0.03), edgecolor='#BDC3C7')

plt.tight_layout()
plt.savefig('KEGG_Combined_Figure.png', dpi=300,
            bbox_inches='tight', facecolor='white')
plt.show()
print("✅ Saved: KEGG_Combined_Figure.png")

df_export = df_all[[
    'Term_clean','Direction','Count','P-Value',
    'Benjamini','Fold Enrichment','neglog10p','User Ids'
]].copy()
df_export.columns = [
    'Pathway','Direction','Gene_Count','P_Value',
    'Benjamini_FDR','Fold_Enrichment','negLog10_Pval','Genes'
]
df_export = df_export.sort_values(['Direction','P_Value']).reset_index(drop=True)
df_export.to_csv('KEGG_All_Pathways_Summary.csv', index=False)
print("✅ Saved: KEGG_All_Pathways_Summary.csv")
display(df_export)

from google.colab import files
import os

outputs = [
    'KEGG_Bar_Chart.png',
    'KEGG_Bubble_Plot.png',
    'KEGG_Combined_Figure.png',
    'KEGG_All_Pathways_Summary.csv'
]

print("⬇️  Downloading all files...\n")
for f in outputs:
    if os.path.exists(f):
        files.download(f)
        print(f"  ✅ {f}")

print("\n🎉 KEGG visualization complete!")
print("📌 Next step → Volcano Plot in Colab")