# -*- coding: utf-8 -*-
"""Password Generator .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18KEGlOBS9baxblVZHKexgk-EPLviWwuL

## Password Generator

 This project is a simple password generator built using Python. It allows the user to create a strong and secure password by specifying the desired length.

The program uses random selection of characters including uppercase and lowercase letters, digits, and special symbols
to generate a random password.

# Features:
- User-defined password length
- Combination of letters, numbers, and symbols
- Generates strong and secure passwords
- Uses Python's random and string modules

Author: Abeera Iftikhar Program: HEC Generative AI Training - Cohort 3
"""

import random
import string

print("🔐 Password Generator")

length = int(input("Enter password length: "))

characters = string.ascii_letters + string.digits + string.punctuation

password = "".join(random.choice(characters) for i in range(length))

print("Your Password:", password)