# -*- coding: utf-8 -*-
"""Currency Converter.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S2sPzTbBqBeVb_79Lhetx6jSgigOsoRo

# 💱 Currency Converter in Python

# Description:
 This project is a simple currency converter built using Python.It allows the user to convert an amount from one currency to another by entering the amount and selecting the source and target currencies.

The program performs calculations using predefined exchange rates
or real-time data (if API is used) to provide accurate conversion results.

# Features:
- User input for amount and currency type
- Supports multiple currencies (USD, PKR, EUR, etc.)
- Accurate conversion using exchange rates
- Simple and user-friendly interface

Author: Abeera Iftikhar
Program: HEC Generative AI Training - Cohort 3
"""

# Currency Converter (Basic Version)

print("💱 Currency Converter")

# Exchange rates (example)
rates = {
    "USD": 1,
    "PKR": 278,
    "EUR": 0.92,
    "INR": 83
}

# User input
amount = float(input("Enter amount: "))
from_currency = input("From currency (USD, PKR, EUR, INR): ").upper()
to_currency = input("To currency (USD, PKR, EUR, INR): ").upper()

# Conversion
usd_amount = amount / rates[from_currency]
converted_amount = usd_amount * rates[to_currency]

# Output
print(f"Converted Amount: {converted_amount:.2f} {to_currency}")